[package]
name = "roxide"
version = "0.1.0"
license = "MIT"
authors = ["Abhinandh S <abhinandhsuby@proton.me>"]
categories = ["command-line-utilities", "filesystem"]
description = "A better rm command for your terminal"
homepage = "https://github.com/abhi-xyz/roxide"
repository = "https://github.com/abhi-xyz/roxide"
keywords = ["cli", "filesystem", "shell", "tool", "utility"]
readme = "README.md"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
